author: Thingon
version: 1.0.0
main: me.justeli.coins.main.Coins
name: CoinDrops
softdepend: [Vault, BeastTokens, JetsMinions, WildStacker]
api-version: 1.13
commands:
  coins:
    aliases: [coin, withdraw]